# Generated by Django 5.0.6 on 2024-06-20 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Roll', models.IntegerField(null=True)),
                ('Name', models.CharField(max_length=250)),
                ('Class', models.IntegerField(null=True)),
                ('Subject', models.CharField(max_length=250)),
            ],
        ),
    ]
