# Generated by Django 5.0.6 on 2024-06-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='Student_photo',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
