# Generated by Django 5.0.6 on 2024-06-24 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_students_student_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentsDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dream', models.CharField(max_length=250)),
                ('skill', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='students',
            name='censorDetails',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studentsDetails', to='myapp.studentsdetails'),
        ),
    ]
