# Generated by Django 5.0.6 on 2024-06-24 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_studentsdetails_students_censordetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='censorDetails',
            new_name='Std_details',
        ),
    ]
