# Generated by Django 5.0.6 on 2024-06-25 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_censordetails_students_std_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='Std_details',
        ),
        migrations.DeleteModel(
            name='StudentsDetails',
        ),
    ]
